// Common nationalities list
export const nationalities = [
  { label: "United Arab Emirates", value: "AE" },
  { label: "India", value: "IN" },
  { label: "Pakistan", value: "PK" },
  { label: "Bangladesh", value: "BD" },
  { label: "Philippines", value: "PH" },
  { label: "Egypt", value: "EG" },
  { label: "United Kingdom", value: "GB" },
  { label: "United States", value: "US" },
  { label: "Canada", value: "CA" },
  { label: "Australia", value: "AU" },
  { label: "South Africa", value: "ZA" },
  { label: "Lebanon", value: "LB" },
  { label: "Jordan", value: "JO" },
  { label: "Syria", value: "SY" },
  { label: "Sudan", value: "SD" },
  { label: "Yemen", value: "YE" },
  { label: "Saudi Arabia", value: "SA" },
  { label: "Kuwait", value: "KW" },
  { label: "Qatar", value: "QA" },
  { label: "Bahrain", value: "BH" },
  { label: "Oman", value: "OM" },
  { label: "Other", value: "OTHER" },
];
